### ISSUE TITLE
Aufgabe Ivy/Francesca: Usability - bis 20.12.

### ISSUE THREAD

**Issue by isyflow** [lateralstudio/isyflow#2]
Untersucht:
Was soll was auf einer Seite und in den Menus sein?
Was soll wie heissen?
Meldet mit Screenshots alle Usabilitydinge, die umständlich sind.

Im Moment keine Label setzten - mache ich.

**Comment by ivyapril** [comment]
Halloechen, 
also schon mal ein paar Punkte: 
-filtrieren sollte durch 'Suchen' ersetzt werden 
-wenn man ueber das + hovered auf der startseite sollte 'neuer workflow erstellen' erscheinen
-oben in dem header sollte wenn man auf den pfeil neben isylfow2 clickt, nur 'mitgleider' erscheinen und nicht 'isyflow2' solange man nichts mit isyflow2 oeffnen kann
![screen shot 2015-11-28 at 3 54 54 pm](https://cloud.githubusercontent.com/assets/15980020/11452463/6327bdde-95e8-11e5-81a8-6bf26ae78a1c.png) ich wuerde anstatt zweimal 'mitglieder' schreiben einmal 'home' und einmal 'mitglieder' schreiben, so weiss man auch was der utnerschied dazwischen sind 
-auch hier auf der seite 'suchen' anstatt filter
-auf der seite importieren, in einer sprache bleiben 
![screen shot 2015-11-28 at 3 58 21 pm](https://cloud.githubusercontent.com/assets/15980020/11452477/df6ffd34-95e8-11e5-98b2-e4b6fbec31a1.png)
-nicht zweimal 'beschreibung', ich wuerde das oberste stehen lassen und darunter schreiben 'Bitte beschreiben Sie die Aktivitaet' 
-unten gibt es drei icons, da mit hover texten arbeiten damit klar ist was was ist; also bei der uhr ob es start oder end termin etc. ist
- ausserdem wuerde ich das kalendar icon aendern da es schwer als kalendar zu erkennen ist und eher aussieht wie ein geschenk 

-um mitglieder und rollen bei einer aktivitaet zuzufuegen muss man unter settings gehen, das wuerde ich vereinfachen mti einem alleinigen knop 'einfuegen..' 
![screen shot 2015-11-28 at 4 01 46 pm](https://cloud.githubusercontent.com/assets/15980020/11452486/5cac154e-95e9-11e5-977b-82a185da7a56.png)
-ich bin mir nicht sicher warum man hier auf 'aktivitaeten' clicken kann, also warum sich die maus veraendert wenn sich durch das klicke nichts veraendert. 

so das wars dann mal fuers erste, ich hoffe ich hab das gemacht was ich machen sollte.. 
LG Ivy

**Comment by isyflow** [comment]
Super.
Machs aber so:
Für jedes Anliegen ein eigenes Issue - das jetzt so lassen, ab jetzt.

Schönes Wochenende
Manfred

Am 28. November 2015 um 16:05 schrieb ivyapril <notifications@github.com>:
