### ISSUE TITLE
Mitglieder / Mitglieder /twice ?

### ISSUE THREAD

**Issue by isyflow** [lateralstudio/isyflow#6]
-oben in dem header sollte wenn man auf den pfeil neben isylfow2 clickt, nur 'mitglieder' erscheinen und nicht 'isyflow2' solange man nichts mit isyflow2 oeffnen kann

anstatt zweimal 'mitglieder' schreiben einmal 'home' und einmal 'mitglieder' schreiben, so weiss man auch was der unterschied dazwischen sind 

![image](https://cloud.githubusercontent.com/assets/8393165/11614749/0aa2213a-9c4c-11e5-8257-d7e0d7093edb.png)

**Comment by GuillaumeZuff** [comment]
I kept the complete list so that users always see the same menu (always the same -> easier to find the item you're looking for).

Changed the second "Mitglieder" to "Liste" since it shows a list of all the users.
