### ISSUE TITLE
Beschreibung, Beschreibung - 2x, Ikons mit hovertext

### ISSUE THREAD

**Issue by isyflow** [lateralstudio/isyflow#7]
![image](https://cloud.githubusercontent.com/assets/8393165/11614754/2ef157f4-9c4c-11e5-9abf-6c5f645ba745.png)

Nicht zweimal 'beschreibung', ich wuerde das oberste stehen lassen und darunter schreiben 'Bitte beschreiben Sie die Aktivitaet' 
Unten gibt es drei icons, da mit hover texten arbeiten damit klar ist was was ist; also bei der uhr ob es start oder end termin etc. ist

ausserdem wuerde ich das kalendar icon aendern, da es schwer als kalendar zu erkennen ist und eher aussieht wie ein geschenk

**Comment by GuillaumeZuff** [comment]
Removed double "Description", replaced second one with a "No description" message and an edit icon.

Calendar icon can not be easily changed (limited, standard set of icons) - added a "Start date" tooltip to clarify.

Added hover text on the icons on the left.

<img width="617" alt="screen shot 2015-12-07 at 22 18 34" src="https://cloud.githubusercontent.com/assets/3705722/11640030/afc22a04-9d30-11e5-9229-033510e9c1c1.png">

**Comment by isyflow** [comment]
i'm watching you ... an training open sea navigation ...

2015-12-07 22:22 GMT+01:00 Guillaume Zufferey <notifications@github.com>:

**Comment by GuillaumeZuff** [comment]
take care big brother :-)
