### ISSUE TITLE
Aktivitäten and mouse pointer - what should happen if click?

### ISSUE THREAD

**Issue by isyflow** [lateralstudio/isyflow#9]
![image](https://cloud.githubusercontent.com/assets/8393165/11614758/896d4d0a-9c4c-11e5-9e99-fe4edf2562b0.png)

Mouse over "Aktiväten" changes Mouse-Pointer.
But: .... nothing happens while clicking.

**Comment by ivyapril** [comment]
I don't think anything needs to happen, I just think either something happens and the mouse change stays or the mouse doesn't transform into a "click" mouse. If that makes sense.

**Comment by GuillaumeZuff** [comment]
The top right "Aktivitäten" is supposed to be a menu. There is only one item for now, that's probably why it's disturbing.
More items will be added soon (list of activities for each workflow member) and it should then make more sense.
